### ISSUE TITLE
Assertion in narrative_ methods keep failing

### ISSUE THREAD

**Issue by FrancyJGLisboa** [denisabd/narrator#2] opened 2023-08-08 11:19 UTC
Hi. Nice work! 
I've noticed that even after changing the data types to meet narrative_ requirements, I still get the same data type error. For example, for narrative_descriptive method, after converting the data types, I get an error message saying that the 'Expected data type for columns X-Xn is either character or numeric, but they are numeric. How come?

**Comment by denisabd** [comment] 2023-08-08 11:48
Hi Francy, thanks a lot for your interest in the package. 
Could you please provide a reproducible example for an error you are getting, using [reprex](https://reprex.tidyverse.org) for example?
Thanks!

**Comment by denisabd** [comment] 2024-01-06 10:13
Closing the issue since to example provided, feel free to re-open.

**Closed as completed by denisabd** 2024-01-06 10:13 UTC
